FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:latest
ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Europe/Oslo

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get upgrade -y



