version: "3"
services:
  mariadb: 
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: mysql_root
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
      MYSQLD_OPTS: "--skip-name-resolve=0"
    volumes:
      - ~/DashBoard/mariadb/:/var/lib/mysql/
      - ~/DashBoard/.devcontainer/ctfd.sql:/docker-entrypoint-initdb.d/ctfd.sql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: mysql_user
      PMA_PASSWORD: mysql_pass
    ports:
      - 8080:80
    depends_on:
      - mariadb
  app:
    build: 
      context: .
      dockerfile: api/Dockerfile
    user: node
    environment:
      PPMA_HOST: mariadb
      PMA_USER: mysql_user
      PMA_PASSWORD: mysql_pass
      PMA_DB: mysql_db
      PMA_PORT: 3306
    ports:
      - 3010:3010
    depends_on:
      - mariadb
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ..:/app:cached
    command: sleep infinity
    user: node
    ports:
      - 3000:3000
    depends_on:
      - app